export const SEA_API_KEY = "6dbbe663b80242aebccf74d53405d9e2";

export const collections = [
  "pudgypenguins",
  "famous-fox-federation",
  "degods",
  "cega-super-sanics",
  "honeyland-generations-bees",
  "clonex",
  "best-buds",
  "lilpudgys",
  "meekolony",
  "cryptopunks",
  "milady",
  "proof-moonbirds",
  "mfers",
  "azuki",
  "dappie-gang",
  "doodles-official",
  "boredapeyachtclub",
  "sproto-gremlins",
  "guttercatgang",
  "wolf-capital-1",
  "otherside-koda",
  "opepen-edition",
  "otherdeed",
  "bored-ape-kennel-club",
  "degenerate-ape-academy",
  "onchainmonkey",
  "mutant-ape-yacht-club",
];
