export const SEA_API_KEY = "6dbbe663b80242aebccf74d53405d9e2";

export const collections = [
  "aurory",
  "pudgypenguins",
  "degods",
  "honeyland-generations-bees",
  "clonex",
  "best-buds",
  "degen-news-2",
  "goofy-gorilla-gang",
  "lilpudgys",
  "famous-fox-federation",
  "sol-srfr-1",
  "cryptopunks",
  "meekolony",
  "milady",
  "degenerate-trash-pandas",
  "proof-moonbirds",
  "mfers",
  "azuki",
  "dappie-gang",
  "home-owners-associations",
  "doodles-official",
  "boredapeyachtclub",
  "sproto-gremlins",
  "cega-super-sanics",
  "guttercatgang",
  "wolf-capital-1",
  "otherside-koda",
  "honeyland-sol",
  "opepen-edition",
  "otherdeed",
  "bored-ape-kennel-club",
  "degenerate-ape-academy",
  "onchainmonkey",
  "mutant-ape-yacht-club",
];
