export const SEA_API_KEY = "6dbbe663b80242aebccf74d53405d9e2";

export const collections = [
  "pudgypenguins",
  "degods",
  "clonex",
  "lilpudgys",
  "cryptopunks",
  "milady",
  "proof-moonbirds",
  "mfers",
  "azuki",
  "doodles-official",
  "boredapeyachtclub",
  "sproto-gremlins",
  "guttercatgang",
  "otherside-koda",
  "opepen-edition",
  "otherdeed",
  "bored-ape-kennel-club",
  "onchainmonkey",
  "mutant-ape-yacht-club",
  "winds-of-yawanawa",
  "pudgyrods",
];
